# Site settings
title: Photography
email: your-email@domain.com
url: https://example.github.io
description: "My name is Tanner Gragg and I am a photographer from Columbus, Ohio! I began my photography journey in late 2018 when I recieved my first camera, a Canon EOS Rebel T6 as a Christmas gift. Since then I found that I have a love and passion for photography!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Tanner Gragg Photography

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://instagram.com/tgraggphotography
  - title: facebook
    url: https://facebook.com/tgraggphotography
  # - title: stack-overflow
   # url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
   # url: http://bitbucket.org/jekyll
  # - title: github
   # url: https://github.com/IronSummitMedia/startbootstrap 

# Build settings
markdown: kramdown
permalink: pretty
